# Generated by Django 4.2.2 on 2023-12-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('overall', models.IntegerField(default=0)),
                ('shooting', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('fitness', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=200)),
                ('team2_name', models.CharField(max_length=200)),
                ('team_size', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
